Repository antlr/intellij-plugin-v4, pull requests merged in 2022-05, with the labels that each got.

#520 Avoid closing preview panel when file switching
  src/main/java/org/antlr/intellij/plugin/ANTLRv4PluginController.java
Labels: enhancement, comp:preview

#551 rm token viewer from the preview panel and don't redraw parse tree for every input character.
  .github/workflows/gradle.yml
  src/main/antlr/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4
  src/main/java/org/antlr/intellij/plugin/ANTLRv4ExternalAnnotator.java
  src/main/java/org/antlr/intellij/plugin/ANTLRv4IconProvider.java
  src/main/java/org/antlr/intellij/plugin/ANTLRv4PluginController.java
  src/main/java/org/antlr/intellij/plugin/actions/AnnotationIntentActionsFactory.java
  src/main/java/org/antlr/intellij/plugin/actions/ExtractRuleAction.java
  src/main/java/org/antlr/intellij/plugin/folding/ANTLRv4FoldingBuilder.java
  src/main/java/org/antlr/intellij/plugin/parsing/LexerWatchdog.java
  src/main/java/org/antlr/intellij/plugin/parsing/ParsingUtils.java
  src/main/java/org/antlr/intellij/plugin/preview/AltLabelTextProvider.java
  src/main/java/org/antlr/intellij/plugin/preview/HierarchyViewer.java
  src/main/java/org/antlr/intellij/plugin/preview/InputPanel.java
  src/main/java/org/antlr/intellij/plugin/preview/ParseTreeContextualMenu.java
  src/main/java/org/antlr/intellij/plugin/preview/ParsingResultSelectionListener.java
  src/main/java/org/antlr/intellij/plugin/preview/PreviewPanel.java
  src/main/java/org/antlr/intellij/plugin/preview/ShowAmbigTreesDialog.java
  src/main/java/org/antlr/intellij/plugin/preview/TokenStreamViewer.java
  src/main/java/org/antlr/intellij/plugin/preview/UberTreeViewer.java
  src/main/java/org/antlr/intellij/plugin/psi/TokenSpecNode.java
  src/main/java/org/antlr/intellij/plugin/structview/ANTLRv4StructureViewElement.java
  src/main/java/org/antlr/intellij/plugin/validation/AddTokenDefinitionFix.java
  src/test/java/org/antlr/intellij/plugin/psi/GrammarElementRefTest.java
  src/test/resources/parser/SqlBase.g4
Labels: comp:preview, performance

#552 Fix parsing of rule with option, fix #549
  src/main/antlr/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4
Labels: comp:grammar-editor, cleanup

#557 Live templates were not appearing.
  gradle.properties
  src/main/java/org/antlr/intellij/plugin/parsing/ParsingUtils.java
  src/main/resources/META-INF/plugin.xml
Labels: bug, comp:grammar-editor
